export const countryTimeZone = {
    "Colombia": "America/Bogota",
    "Mexico": "America/Mexico_City",
    "Argentina": "America/Argentina/Buenos_Aires",
    "Peru": "America/Lima",
    "Chile": "America/Santiago",
    "España": "Europe/Madrid",
    "Estados Unidos": "America/New_York",
    "Brasil": "America/Sao_Paulo",
    "Ecuador": "America/Guayaquil",
    "Bolivia": "America/La_Paz",
    "Uruguay": "America/Montevideo",
    "Paraguay": "America/Asuncion",
    "Venezuela": "America/Caracas",
    "Panama": "America/Panama",
    "Costa Rica": "America/Costa_Rica",
    "Guatemala": "America/Guatemala",
    "Honduras": "America/Tegucigalpa",
    "El Salvador": "America/El_Salvador",
    "Nicaragua": "America/Managua",
    "Cuba": "America/Havana",
    "Republica Dominicana": "America/Santo_Domingo",
    "Puerto Rico": "America/Puerto_Rico",
    "Canada": "America/Toronto",
    "Reino Unido": "Europe/London",
    "Francia": "Europe/Paris",
    "Italia": "Europe/Rome",
    "Alemania": "Europe/Berlin",
    "Portugal": "Europe/Lisbon",
    "Suiza": "Europe/Zurich",
    "Países Bajos": "Europe/Amsterdam",
    "Bélgica": "Europe/Brussels",
    "Suecia": "Europe/Stockholm",
    "Noruega": "Europe/Oslo",
    "Dinamarca": "Europe/Copenhagen",
    "Finlandia": "Europe/Helsinki",
    "Rusia": "Europe/Moscow",
    "China": "Asia/Shanghai",
    "Japón": "Asia/Tokyo",
    "India": "Asia/Kolkata",
    "Australia": "Australia/Sydney",
    "Nueva Zelanda": "Pacific/Auckland",
    "Sudáfrica": "Africa/Johannesburg",
    "Egipto": "Africa/Cairo",
    "Marruecos": "Africa/Casablanca",
    "Turquía": "Europe/Istanbul",
    "Arabia Saudita": "Asia/Riyadh",
    "Emiratos Árabes Unidos": "Asia/Dubai",
    "Israel": "Asia/Jerusalem",
  };
  